In [1]:
import numpy as np
import pandas as pd
import csv
import os
import glob
import datetime

- 전처리에 필요한 **package 불러오기**
<br>
***

In [2]:
sorted(os.listdir('../data/'))

['EAST-1_200607_profile_chemical_rosette.csv',
 'EAST-1_201108_profile_chemical_rosette.csv',
 'EAST-1_201203_profile_chemical_rosette.csv',
 'EAST-1_201210_profile_chemical_rosette.csv',
 'EAST-1_201303_profile_chemical_rosette.csv',
 'EAST-1_201404_profile_chemical_rosette.csv',
 'EAST-1_201404_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_1998_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_1999_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2000_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2001_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2002_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2004_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2006_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2007_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2008_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2009_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2011_profile_chemical_unknown.csv',
 '폐기물 배출해역 조사_2012_profile_chemical_unknown.csv']

- **JOISS**에서 다운로드 받은 자료를 오름차순 정렬
<br>
---

In [3]:
file_list = glob.glob("../data/*.csv")

list_of_dataframes = []
for filename in file_list:
    list_of_dataframes.append(pd.read_csv(filename, encoding = 'euc-kr', skiprows = 26))
    
merged_df = pd.concat(list_of_dataframes, join = 'outer')

In [4]:
merged_df

,project_name,station,yyyy-mm-dd hh:mm:ss,Longitude [degrees_east],Latitude [degrees_south],bot.depth[m],수심(m),염분,sal_qc,수온[℃],...,폴리염화바이페닐-101[μg/kg],pcb101_qc,폴리염화바이페닐-118[μg/kg],pcb118_qc,폴리염화바이페닐-138[μg/kg],pcb138_qc,폴리염화바이페닐-153[μg/kg],pcb153_qc,폴리염화바이페닐-180[μg/kg],pcb180_qc
0,2006년 7월 관할해역 집중조사,B1,2006-07-13 00:00:00,129.494167,37.248167,0,0.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006년 7월 관할해역 집중조사,B1,2006-07-13 00:37:00,129.494167,37.248167,0,100.35,34.00,1.0,2.2800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006년 7월 관할해역 집중조사,B1,2006-07-13 00:38:00,129.494167,37.248167,0,49.39,34.02,1.0,4.6000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2006년 7월 관할해역 집중조사,B1,2006-07-13 00:38:00,129.494167,37.248167,0,74.26,34.01,1.0,2.7600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006년 7월 관할해역 집중조사,B1,2006-07-13 00:39:00,129.494167,37.248167,0,29.79,33.95,1.0,7.6500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,폐기물 배출해역 조사,서해병-B,2012-08-21 6:47,124.391667,35.335000,0,50.00,NaN,1.0,8.5600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,폐기물 배출해역 조사,서해병-A,2012-02-28 14:02,124.391667,36.330000,0,0.00,NaN,1.0,6.3296,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,폐기물 배출해역 조사,서해병-A,2012-02-28 14:02,124.391667,36.330000,0,50.00,NaN,1.0,6.2977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,폐기물 배출해역 조사,서해병-A,2012-08-21 15:05,124.391667,36.330000,0,0.00,NaN,1.0,28.1800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,폐기물 배출해역 조사,서해병-A,2012-08-21 15:05,124.391667,36.330000,0,50.00,NaN,1.0,8.6100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- 경로 내 csv 파일 모두 불러오기
<br>
---

In [5]:
merged_df['yyyy-mm-dd hh:mm:ss'] = pd.to_datetime(merged_df['yyyy-mm-dd hh:mm:ss'], format='%Y-%m-%d %H:%M:%S', errors='raise')

In [6]:
merged_df['mon/day/yr'] = merged_df['yyyy-mm-dd hh:mm:ss'].dt.strftime('%m-%d-%Y')

In [7]:
merged_df['hh:mm'] = merged_df['yyyy-mm-dd hh:mm:ss'].dt.strftime('%H:%M')

- 날짜 및 시간 형식 변경하기
<br>
---

In [8]:
merged_df['염분'] = merged_df['염분'].fillna(0)
merged_df['염분[psu]'] = merged_df['염분[psu]'].fillna(0)
merged_df['염분[‰]'] = merged_df['염분[‰]'].fillna(0)

In [9]:
merged_df['Salinity [PSU]'] = (merged_df['염분']+ merged_df['염분[psu]'] + merged_df['염분[‰]'])
merged_df['Salinity [PSU]'] = merged_df['Salinity [PSU]'].replace(0, np.NaN)

- 서로 data 형태가 일치하지 않는 항목 통일하기
<br>
---

In [10]:
merged_df.rename(columns = {"project_name":"Cruise", "station":"Station", "Latitude [degrees_south]":"Latitude [degrees_north]", "bot.depth[m]":"Bot. Depth [m]", "수심(m)":"Depth [m]", "수온[℃]":"Temperature [℃]", 
                            "potential density-1000[kg/m3]":"Sigma-t [kg/m3]", "용존산소[ml/L]":"DO[μmol/kg]", "용존산소[mg/L]":"DO[mg/l]", "클로로필-a[mg/m3]":"Chl.a[mg/m3]", "클로로필-a[μg/L]":"Chl.a[μg/L]", 
                            "알칼리도[μmol/kg]":"Alk[μmol/kg]", "수소이온농도[무단위]":"pH", "인산염인[μmol/kg]":"PO4-[μmol/kg]", "인산염인[mg/L]":"PO4-[mg/L]", "암모니아성 질소[μmol/kg]":"NH4+[μmol/kg]",
                            "암모니아성 질소[mg/L]":"NH4+[mg/L]", "아질산성질소[mg/L]":"NO2-[μmol/kg]", "아질산성 질소 + 질산성 질소[μmol/kg]":"NO2-+NO3-[μmol/kg]", "질산성질소[mg/L]":"NO3-[μmol/kg]", 
                            "이산화규소[μmol/kg]":"SiO4-[μmol/kg]", "총질소[wt.%]":"TN", "총인[mg/L]":"TP", "ISUSnitrate[μg/L]":"ISUS nitrate[μmol/kg]", "입자성 유기탄소[μg/L]":"POC",
                            "용존 유기탄소[μM]":"DOC", "용존 무기 탄소[μmol/kg]":"DIC", "총유기탄소[mg/L]":"TOC", "입자성 유기질소[μg/L]":"PON", "유색 용존 유기물_C1[QSU]":"CDOM_C1[QSU]",
                            "유색 용존 유기물_C2[QSU]":"CDOM_C2[QSU]", "유색 용존 유기물_C3[QSU]":"CDOM_C3[QSU]", "유색 용존 유기물_C4[QSU]":"CDOM_C4[QSU]", "부유물질 농도[mg/L]":"SS[mg/L]",
                            "화학적산소요구량[mg/L]":"COD[mg/L]", "투명도[m]":"Transparency[m]",   "구리[μg/kg]":"Cu[μg/kg]", "납[μg/kg]":"Pb[μg/kg]", "아연[μg/kg]":"Zn[μg/kg]",
                            "카드뮴[μg/kg]":"Cd[μg/kg]", "6가크롬[μg/kg]":"Cr6+[μg/kg]", "비소[μg/kg]":"As[μg/kg]"},inplace = True)

- 컬럼명 변환하기
<br>
---

In [11]:
merged_df['Depth [m]'] = merged_df['Depth [m]'].replace(-999.99,50)
merged_df['Depth [m]'] = merged_df['Depth [m]'].replace(-9.99,0)

- 특정 데이터 변환
<br>
---

In [12]:
merged_df = merged_df[['Cruise', 'Station', 'mon/day/yr', 'hh:mm', 'Longitude [degrees_east]', 'Latitude [degrees_north]', 'Depth [m]', 'Temperature [℃]', 
         'wtrtmp_qc', 'Salinity [PSU]', 'sal_qc', 'Sigma-t [kg/m3]', 'potden_qc', 'DO[μmol/kg]', 'DO[mg/l]', 'disoxy_qc', 'Chl.a[mg/m3]', 'Chl.a[μg/L]','chla_qc', 
         'Alk[μmol/kg]', 'alkal_qc', 'pH', 'hydioncon_qc', 'PO4-[μmol/kg]', 'PO4-[mg/L]', 'po4p_qc', 'NH4+[μmol/kg]', 'NH4+[mg/L]', 'amn_qc', 'NO2-[μmol/kg]', 
         'nitnit_qc', 'NO2-+NO3-[μmol/kg]', 'no2andno3_qc', 'NO3-[μmol/kg]', 'natnit_qc', 'SiO4-[μmol/kg]', 'sio2_qc', 'TN', 'tn_qc', 'TP', 'totp_qc', 
         'ISUS nitrate[μmol/kg]', 'isusn_qc', 'POC', 'parorgc_qc', 'DOC', 'disorgc_qc', 'DIC', 'dic_qc', 'TOC', 'totorgc_qc', 'PON', 'parorgn_qc',
         'CDOM_C1[QSU]', 'cdom_c1_qc', 'CDOM_C2[QSU]', 'cdom_c2_qc', 'CDOM_C3[QSU]', 'cdom_c3_qc', 'CDOM_C4[QSU]', 'cdom_c4_qc', 'SS[mg/L]', 'sussed_qc',
         'COD[mg/L]', 'cheoxydem_qc', 'Transparency[m]', 'tr_qc', 'Cu[μg/kg]', 'cu_qc', 'Pb[μg/kg]', 'pb_qc', 'Zn[μg/kg]', 'zn_qc', 'Cd[μg/kg]',
         'cd_qc', 'Cr6+[μg/kg]', 'hexchum_qc', 'As[μg/kg]', 'as_qc']]

In [13]:
merged_df = merged_df.dropna(subset = ['Depth [m]', 'Temperature [℃]', 'Salinity [PSU]'], how = 'any', axis = 0)

In [14]:
df = merged_df.fillna('NaN')

- 특정 칼럼에 결측값이 있을 경우 제거하기
<br>
---

In [15]:
df = pd.DataFrame(df)

In [16]:
df.to_csv("../data/JOISS_data_preprocessing.csv", encoding = 'euc-kr')

- 전처리가 끝난 파일을 csv로 내보내기